HRMS/Controllers/QualificationController.cs
using Data.HRMS;
using Library.Core.Services;
using Services.Look;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Services.HRMS;

namespace HRMS.Controllers
{
    public class QualificationController : Controller
    {
        // GET: Qualification
        LookQualificationService lookQualificationService = new LookQualificationService();
        [CustomAuthorize(Permission = "CreateQualification")]
        public JsonResult New(LookQualification qualification)
        {
            var result = new Result<LookQualification>();
            try
            {
                var insertion = lookQualificationService.InsertQualification(qualification);
                if (insertion.ResultType.Equals(ResultType.Success))
                {                    
                    result.Data = insertion.Data;
                    result.ResultType = ResultType.Success;
                }
                else
                {
                    result.Data = null;
                    result.ResultType = ResultType.Failure;
                }
            }
            catch(Exception e)
            {
                result.Data = null;
                result.ResultType = ResultType.Exception;
                result.Message = e.GetOriginalException().Message;
                result.Exception = e;
            }
            
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [CustomAuthorize(Permission = "ViewCreateQualification")]
        public ActionResult Create(long? id)
        {
            var qualificationType = lookQualificationService.QualificationTypeList();
            if (qualificationType.ResultType.Equals(ResultType.Exception))
                return RedirectToAction("No505", "Error");
              ViewBag.QualificationType = new SelectList(qualificationType.Data, "LookQualificationTypeId", "QualificationType");
            if (id.IsNotNull())
            {
                long desgnationId = id ?? 0;
                var designation = lookQualificationService.GetQualification(desgnationId);
                if (designation.ResultType.Equals(ResultType.Exception))
                    return RedirectToAction("No505", "Error");
                if (designation.Data.IsNotNull())
                {
                    return View(designation.Data);
                }
                else
                {
                    return RedirectToAction("List");
                }
            }

            return View();
        }
        [CustomAuthorize(Permission = "EditCreateQualification")]
        [HttpPost]
        public ActionResult Create(LookQualification qualification)
        {
            if (qualification.LookQualificationId.Equals(0) || qualification.LookQualificationId.Equals(null))
            {
                var insertion = lookQualificationService.InsertQualification(qualification);
                if (insertion.ResultType.Equals(ResultType.Exception))
                {
                    return RedirectToAction("No505", "Error");
                }
            }
            else
            {
                var updation = lookQualificationService.UpdateQualification(qualification);
                if (updation.ResultType.Equals(ResultType.Exception))
                {

                    return RedirectToAction("No505", "Error");
                }
            }
            return RedirectToAction("QualificationList");
        }
        [CustomAuthorize(Permission = "ViewCreateQualification")]
        public ActionResult QualificationTypeCreate(long? id)
        {
            if (id.IsNotNull())
            {
                long desgnationId = id ?? 0;
                var designation = lookQualificationService.GetQualificationType(desgnationId);
                if (designation.ResultType.Equals(ResultType.Exception))
                    return RedirectToAction("No505", "Error");
                if (designation.Data.IsNotNull())
                {
                    return View(designation.Data);
                }
                else
                {
                    return RedirectToAction("QualificationTypeList");
                }
            }

            return View();
        }
        [HttpPost]
        [CustomAuthorize(Permission = "EditCreateQualification")]
        public ActionResult QualificationTypeCreate(LookQualificationType qualification)
        {
            if (qualification.LookQualificationTypeId.Equals(0) || qualification.LookQualificationTypeId.Equals(null))
            {
                var insertion = lookQualificationService.InsertQualification(qualification);
                if (insertion.ResultType.Equals(ResultType.Exception))
                {
                    return RedirectToAction("No505", "Error");
                }
            }
            else
            {
                var updation = lookQualificationService.UpdateQualification(qualification);
                if (updation.ResultType.Equals(ResultType.Exception))
                {

                    return RedirectToAction("No505", "Error");
                }
            }
            return RedirectToAction("QualificationList");
        }
        [CustomAuthorize(Permission = "ViewQualificationList")]
        public ActionResult QualificationList()
        {
            //LookQualification
            
            return View(lookQualificationService.QualificationList().Data);
        }

        [CustomAuthorize(Permission = "ViewQualificationList")]
        public ActionResult QualificationTypeList()
        {
            //LookQualification

            return View(lookQualificationService.QualificationTypeList().Data);
        }
    }
}

HRMS/Views/Qualification/Create.cshtml
@model Data.HRMS.LookQualification
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="content-wrapper">
    <h3>
        Add Qualification
    </h3>
    <div class="row">
        <div class="col-sm-6 col-lg-offset-3">
            <!-- START panel-->
            <div class="panel panel-default">
                <div class="panel-heading"> Qualification info</div>
                <div class="panel-body">
                    @using (Html.BeginForm("Create", "Qualification", FormMethod.Post, new { role = "form", id = "frmInsert" }))
                    {
                        <div class="form-group">
                            <label>Profession Name<span class='required'>*</span></label>
 
                        @Html.DropDownListFor(m => m.LookQualificationTypeId, ViewBag.QualificationType as SelectList, new { @class = "form-control", placeholder = "Qualification" })
                        </div>
                        <div class="form-group">
                            <label>Qualification Name<span class='required'>*</span></label>
                            @Html.TextBoxFor(m => m.QualificationName, new { @class = "form-control", placeholder = "Qualification Name" })
                            @Html.HiddenFor(m => m.LookQualificationId)
                        </div>
                        <div class="col-sm-12 text-center">
                            <input type="submit" class="btn btn-sm btn-primary" value="Save" />
                        </div>
                    }

                </div>
            </div>
            <!-- END panel-->
        </div>

    </div>
</div>
<script>
    // just for the demos, avoids form submit
   /* jQuery.validator.setDefaults({
        debug: true,
        success: "valid"
    });*/
    $("#frmInsert").validate({
        rules: {
            LookDepartmentId: {
                required: true
            },
            DesignationName: {
        required: true
    }
        },
        submitHandler: function (form) {
            form.submit();
        }
    });
</script>

HRMS/Views/Qualification/QualificationList.cshtml
@model List<Data.HRMS.LookQualification>
@{
    ViewBag.Title = "QualificationList";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<div class="content-wrapper">
    <h3>
        Qualification
        <a href="@Url.Action("Create","Qualification")">
            <button type="button" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>&nbsp;&nbsp;&nbsp;Add New Qualification</button>
        </a>
    </h3>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    QualificationInfo
                </div>
                <div class="panel-body">
                    <table id="datatable1" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>S.NO.</th>
                                <th>Qualification Name</th>
                                <th>Qualification Type</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                var count = 0;
                                foreach (var item in Model)
                                {
                                    count = count + 1;

                                    <tr class="gradeX">
                                        <td>@count</td>
                                        <td>@item.QualificationName</td>
                                        <td>@item.LookQualificationTypeId</td>
                                        <td class="table_action">
                                            <a href="@Url.Action("Create","Qualification",new {id=item.LookQualificationId })" title="Edit Qualification"><em class="icon-note" style="font-size: 18px;"></em></a>
                                            <em class="delete_record icon-close" title="Delete Qualification" style="font-size:18px;color:red" rel="51"></em>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                    @*<div class="row" style="margin-top: 10px;">
                            <div class="col-xs-6">
                                <div class="dataTables_info" id="datatable1_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                            </div><div class="col-xs-6">
                                <div class="dataTables_paginate paging_simple_numbers" id="datatable1_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button previous disabled" aria-controls="datatable1" tabindex="0" id="datatable1_previous">
                                            <a href="#">Previous</a>
                                        </li>
                                        <li class="paginate_button active" aria-controls="datatable1" tabindex="0"><a href="#">1</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">2</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">3</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">4</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">5</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">6</a></li>
                                        <li class="paginate_button next" aria-controls="datatable1" tabindex="0" id="datatable1_next"><a href="#">Next</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>*@
                </div>
            </div>
        </div>
    </div>

</div>
<script type="text/javascript">
    $(document).ready(function () {

        //$(document).off("click", ".paginate_button").on("click", ".paginate_button", function (event) {
        //    //event.preventDefault();
        //    alert('wasim');

        //});

    });



</script>

HRMS/Views/Qualification/QualificationTypeList.cshtml
@model List<Data.HRMS.LookQualificationType>
@{
    ViewBag.Title = "QualificationTypeList";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="content-wrapper">
    <h3>
        Qualification
        <a href="@Url.Action("QualificationTypeCreate","Qualification")">
            <button type="button" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>&nbsp;&nbsp;&nbsp;Add New Qualification</button>
        </a>
    </h3>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    QualificationInfo
                </div>
                <div class="panel-body">
                    <table id="datatable1" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>S.NO.</th>
                                <th>Qualification Type</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                var count = 0;
                                foreach (var item in Model)
                                {
                                    count = count + 1;

                                    <tr class="gradeX">
                                        <td>@count</td>
                                        <td>@item.QualificationType</td>                                      
                                        <td class="table_action">
                                            <a href="@Url.Action("QualificationTypeCreate","Qualification",new {id=item.LookQualificationTypeId })" title="Edit QualificationType"><em class="icon-note" style="font-size: 18px;"></em></a>
                                            <em class="delete_record icon-close" title="Delete QualificationType" style="font-size:18px;color:red" rel="51"></em>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                    @*<div class="row" style="margin-top: 10px;">
                            <div class="col-xs-6">
                                <div class="dataTables_info" id="datatable1_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                            </div><div class="col-xs-6">
                                <div class="dataTables_paginate paging_simple_numbers" id="datatable1_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button previous disabled" aria-controls="datatable1" tabindex="0" id="datatable1_previous">
                                            <a href="#">Previous</a>
                                        </li>
                                        <li class="paginate_button active" aria-controls="datatable1" tabindex="0"><a href="#">1</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">2</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">3</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">4</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">5</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">6</a></li>
                                        <li class="paginate_button next" aria-controls="datatable1" tabindex="0" id="datatable1_next"><a href="#">Next</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>*@
                </div>
            </div>
        </div>
    </div>

</div>
<script type="text/javascript">
    $(document).ready(function () {

        $(document).off("click", ".paginate_button").on("click", ".paginate_button", function (event) {
            //event.preventDefault();
            alert('wasim');

        });

    });



</script>