HRMS/Controllers/PublicHolidaysController.cs
using Data.HRMS;
using Library.Core.Services;
using Services.HRMS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRMS.Controllers
{
    public class PublicHolidaysController : Controller
    {
        PublicHolidaysService publicHolidaysService = new PublicHolidaysService();
        // GET: PublicHolidays
        [CustomAuthorize(Permission = "ViewCreateHolidays")]
        public ActionResult Create(long? id)
        {
            try
            {  
                if (id.IsNotNull())
                {
                    var publicHoliday = publicHolidaysService.GetPublicHolidayById(id ?? 0);
                    if (publicHoliday.ResultType.Equals(ResultType.Success))
                    {
                        if (publicHoliday.Data.IsNotNull())
                        {
                            return View(publicHoliday.Data);
                        }
                        return RedirectToAction("HolidaysList");
                    }
                    else
                    {
                        return RedirectToAction("No505", "Error");
                    }
                }
                else
                {
                    // return RedirectToAction("DepartmentList");
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("No505", "Error");
            }
        }
        [CustomAuthorize(Permission = "EditHolidays")]
        [HttpPost]
        public ActionResult Create(PublicHoliday publicHoliday)
        {
            //LookDepartmentService lookDepartmentService = new LookDepartmentService();
            if (publicHoliday.PublicHolidayId > 0)
            {
                publicHolidaysService.UpdatePublicHoliday(publicHoliday);
            }
            else
            {
                publicHolidaysService.CreatePublicHoliday(publicHoliday);

            }
            return RedirectToAction("HolidaysList");
        }
        [CustomAuthorize(Permission = "ViewHolidaysList")]
        public ActionResult HolidaysList()
        {  
            var publicHolidaysList = publicHolidaysService.PublicHolidaytList();
            return View(publicHolidaysList.Data);
        }
    }
}

HRMS/Views/PublicHolidays/HolidaysList.cshtml
@model List<Data.HRMS.PublicHoliday>
@{
    ViewBag.Title = "HolidaysList";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<div class="content-wrapper">
    <h3>
        PublicHolidays
        <a href="@Url.Action("Create","PublicHolidays")">
            <button type="button" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>&nbsp;&nbsp;&nbsp;Add New PublicHoliday</button>
        </a>
    </h3>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    PublicHolidayInfo
                </div>
                <div class="panel-body">
                    <table id="datatable1" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>S.NO.</th>
                                <th>Date</th>
                                <th>Detail</th>
                                <th>Status</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                var count = 0;
                                foreach (var item in Model)
                                {
                                    count = count + 1;
                                    <tr class="gradeX">
                                        <td>@count</td>
                                        <td>@item.HoIidayDate</td>
                                        <td>@item.Detail</td>
                                        <td>@item.IsActive</td>
                                        <td class="table_action">
                                            <a href="@Url.Action("Create","PublicHolidays",new {id=item.PublicHolidayId })" title="Edit PublicHoliday"><em class="icon-note" style="font-size: 18px;"></em></a>
                                            <em class="delete_record icon-close" title="Delete PublicHoliday" style="font-size:18px;color:red" rel="51"></em>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                    @*<div class="row" style="margin-top: 10px;">
                            <div class="col-xs-6">
                                <div class="dataTables_info" id="datatable1_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                            </div><div class="col-xs-6">
                                <div class="dataTables_paginate paging_simple_numbers" id="datatable1_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button previous disabled" aria-controls="datatable1" tabindex="0" id="datatable1_previous">
                                            <a href="#">Previous</a>
                                        </li>
                                        <li class="paginate_button active" aria-controls="datatable1" tabindex="0"><a href="#">1</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">2</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">3</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">4</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">5</a></li>
                                        <li class="paginate_button " aria-controls="datatable1" tabindex="0"><a href="#">6</a></li>
                                        <li class="paginate_button next" aria-controls="datatable1" tabindex="0" id="datatable1_next"><a href="#">Next</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>*@
                </div>
            </div>
        </div>
    </div>

</div>
<script type="text/javascript">
    $(document).ready(function () {

        //$(document).off("click", ".paginate_button").on("click", ".paginate_button", function (event) {
        //    //event.preventDefault();
        //    alert('wasim');

        //});

    });



</script>