HRMS/Controllers/DepartmentController.cs
using Data.HRMS;
using Library.Core.Services;
using Services.Look;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRMS.Controllers
{
    public class DepartmentController : Controller
    {
        [CustomAuthorize(Permission = "ViewCreateDepartment")]
        public ActionResult Create(long? id)
        {
            try
            {
                LookDepartment modelDepartment = new LookDepartment();
                LookDepartmentService lookDepartmentService = new LookDepartmentService();
                if (id.IsNotNull())
                {
                    var department = lookDepartmentService.GetDepartmentById(id ?? 0);
                    if (department.ResultType.Equals(ResultType.Success))
                    {
                        if (department.Data.IsNotNull())
                        {
                            var dbDepartment = department.Data;
                            modelDepartment.DepartmentName = dbDepartment.DepartmentName;
                            return View(department.Data);
                        }
                        return RedirectToAction("DepartmentList");
                    }
                    else
                    {
                        return RedirectToAction("No505", "Error");
                    }
                }
                else
                {
                   // return RedirectToAction("DepartmentList");
                    return View();
                }
            }
            catch
            {
                return RedirectToAction("No505", "Error");
            }
        }
        [CustomAuthorize(Permission = "EditCreateDepartment")]
        [HttpPost]
        public ActionResult Create(LookDepartment lookDepartment)
        {
            LookDepartmentService lookDepartmentService = new LookDepartmentService();
            if (lookDepartment.LookDepartmentId > 0)
            {
                lookDepartmentService.UpdateDepartment(lookDepartment);
            }
            else
            {
                lookDepartmentService.CreateDepartment(lookDepartment);

            }
            return RedirectToAction("DepartmentList");
        }
        [CustomAuthorize(Permission = "ViewDepartmentList")]
        public ActionResult DepartmentList()
        {
            LookDepartmentService lookDepartmentService = new LookDepartmentService();
            var departmentList = lookDepartmentService.DepartmentList();          
            return View(departmentList.Data);          
        }




    }
}

HRMS/Controllers/OrganizationController.cs
using Data.HRMS;
using Services.Look;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Core.Services;
using Services.HRMS;


namespace HRMS.Controllers
{
    public class OrganizationController : Controller
    {
        // GET: Organization
        public ActionResult CreateDepartment()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateDepartment(LookDepartment lookDepartment)
        {
            LookDepartmentService lookDepartmentService = new LookDepartmentService();
            lookDepartmentService.CreateDepartment(lookDepartment);
            return View();
        }

        public ActionResult GetDepartment()
        {
            return View();
        }
		  [CustomAuthorize(Permission = "ViewCreateOrganization")]
        [HttpGet]
        public ActionResult Organization(long? id)
        {
            LookOrganization organization = new LookOrganization();
            if (!(id.Equals(0) || id.IsNull()))
            {
                LookOrganizationService organizationService = new LookOrganizationService();
                var exsistingOrganization = organizationService.GetOrganization(id ?? 0);
                if (exsistingOrganization.ResultType.Equals(ResultType.Exception))
                {
                    return RedirectToAction("No505", "Error");
                }
                if (exsistingOrganization.Data.IsNull())
                {
                    ViewBag.Alert = "Sorry, Not Found... Why not enter a new one?";
                }
                organization = exsistingOrganization.Data;
            }
            return View(organization);
        }
        [CustomAuthorize(Permission = "EditCreateOrganization")]
        [HttpPost]
        public ActionResult Organization(LookOrganization organization)
        {
            LookOrganizationService organizationService = new LookOrganizationService();
            if (organization.LookOrganizationId.Equals(0) || organization.LookOrganizationId.IsNull())
            {
                var response = organizationService.CreateOrganization(organization);
                if (response.ResultType.Equals(ResultType.Exception))
                {
                    return RedirectToAction("No505", "Error");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                var response = organizationService.UpdateOrganization(organization);
                if (response.ResultType.Equals(ResultType.Exception))
                {
                    return RedirectToAction("No505", "Error");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
        }

        [CustomAuthorize(Permission = "CreateOrganization")]
        [HttpPost]
        public JsonResult CreateOrganization(LookOrganization organization)
        {
            var result = new Result<LookOrganization>();
            try
            {
                LookOrganizationService organizationService = new LookOrganizationService();
                var response = organizationService.CreateOrganization(organization);
                if (response.ResultType.Equals(ResultType.Exception))
                {
                    result.Data = null;
                    result.ResultType = ResultType.Exception;
                    result.Message = response.Message;
                    result.Exception = response.Exception;
                }
                result.Data = response.Data;
                result.ResultType = ResultType.Success;                
            }

            catch(Exception e) {
                result.Data = null;
                result.ResultType = ResultType.Success;
                result.Message = e.GetOriginalException().Message;
                result.Exception = e;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

HRMS/Views/Organization/CreateDepartment.cshtml
@model Data.HRMS.LookDepartment
@{
    ViewBag.Title = "CreateDepartment";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="content-wrapper">
    <h3>
        Add Departments
    </h3>
    <div class="row">
        <div class="col-sm-6 col-lg-offset-3">
            <!-- START panel-->
            <div class="panel panel-default">
                <div class="panel-heading">Add Department info</div>
                <div class="panel-body">
                    @using (Html.BeginForm("CreateDepartment", "Organization", FormMethod.Post@*, new { @class = "form-horizontal", enctype = "multipart/form-data", id = "frmInsert" }*@))
                    {
                        @*<form role="form">*@
                        <div class="form-group">
                            <label>Department Name</label>
                            @* <input type="email" placeholder="Department Name" class="form-control">*@
                            @Html.TextBoxFor(m => m.DepartmentName, new { @class = "form-control", placeholder = "Department Name" })
                        </div>
                        <div class="col-sm-12 text-center">
                           @* <button type="submit" class="btn btn-sm btn-primary">Submit</button>*@
                            <input type="submit" class="btn btn-sm btn-primary" value="Save" />
                        </div>
                        @*</form>*@
                    }
                </div>
            </div>
            <!-- END panel-->
        </div>

    </div>
</div>

HRMS/Views/Organization/Department.cshtml
@{
    ViewBag.Title = "Department";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="content-wrapper">
    <h3>
        Departments
        <small>Standard and custom elements for any form</small>
    </h3>
    <div class="row">
        <div class="col-sm-8">
            <!-- START panel-->
            <div class="panel panel-default">
                <div class="panel-heading">Stacked form</div>
                <div class="panel-body">
                    <form role="form">
                        <div class="form-group">
                            <label>Email address</label>
                            <input type="email" placeholder="Enter email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" placeholder="Password" class="form-control">
                        </div>                        
                        <button type="submit" class="btn btn-sm btn-default">Submit</button>
                    </form>
                </div>
            </div>
            <!-- END panel-->
        </div>

    </div>
    </div>

HRMS/Views/Organization/Organization.cshtml
@model Data.HRMS.LookOrganization

@{
    ViewBag.Title = "Organization";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    string alert = ViewBag.Alert;
}

<div class="content-wrapper">
    <h3>
        Organization
    </h3>
    <div class="row">
        <div class="col-sm-6 col-lg-offset-3">
            <!-- START panel-->
            <div class="panel panel-default">
                <div class="panel-heading">
                    @if (Model.IsNotNull())
                    {
                        <p> Edit</p>
                    }
                    else
                    {
                        <p> Add</p>
                    }

                    Department info
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("Organization", "Organization", FormMethod.Post@*, new { @class = "form-horizontal", enctype = "multipart/form-data", id = "frmInsert" }*@))
                    {
                        if (alert.IsNotNullOrEmpty())
                        {
                            <p>@alert</p>
                        }
                        <div class="form-group">
                            <label>Organization Name</label>
                            @* <input type="email" placeholder="Department Name" class="form-control">*@
                            @Html.TextBoxFor(m => m.OrganizationName, new { @class = "form-control", placeholder = "Organization Name" })
                        </div>
                        <div class="form-group">
                            <label>Organization URL</label>
                            @* <input type="email" placeholder="Department Name" class="form-control">*@
                            @Html.TextBoxFor(m => m.OrganizationURL, new { @class = "form-control", placeholder = "Organization URL" })
                        </div>
                        <div class="col-sm-12 text-center">
                            @Html.HiddenFor(m => m.LookOrganizationId)
                            <input type="submit" class="btn btn-sm btn-primary" value="Save" />
                        </div>
                    }
                </div>
            </div>
            <!-- END panel-->
        </div>

    </div>
</div>